apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
  labels:
    name: db
    app: voting-app
spec:
  replicas: 1
  template:
    metadata:
      name: db
      labels:
        name: postgres-pod
        app: my-voting-app
    spec:
      containers:
        - name: db
          image: postgres:9.4
          ports:
            - containerPort: 5432
  selector:
    matchLabels:
      name: postgres-pod
      app: my-voting-app