apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: postgres-pod
    app: my-voting-app
spec:
  containers:
    - name: db-service
      image: postgres:9.4
      ports:
        - containerPort: 5432