apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: redis-service
      image: redis
      ports:
        - containerPort: 6379