apiVersion: v1
kind: Deployment
metadata:
  name: redis
  labels:
    name: redis
    app: voting-app
spec:
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        name: redis-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
  selector:
    name: redis-app-pod
    app: demo-voting-app