apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    name: result
    app: voting-app
spec:
  replicas: 3
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: result
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-app