apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    name: vote
    app: voting-app
spec:
  replicas: 3
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: vote
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      name: voting-app-pod
      app: demo-voting-app